"""initial_schema

Revision ID: 90b321684f03
Revises: 
Create Date: 2025-11-10 15:39:34.041272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90b321684f03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables already exist to make this migration idempotent
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'replays' not in existing_tables:
        op.create_table('replays',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('winner_name', sa.String(length=255), nullable=False),
        sa.Column('summary', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'users' not in existing_tables:
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=120), nullable=False),
        sa.Column('display_name', sa.String(length=120), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
        )
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    if 'bots' not in existing_tables:
        op.create_table('bots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('current_version_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['current_version_id'], ['bot_versions.id'], ondelete='SET NULL', use_alter=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'name', name='uq_bot_user_name')
        )
    
    if 'replay_participants' not in existing_tables:
        op.create_table('replay_participants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('replay_id', sa.Integer(), nullable=False),
        sa.Column('bot_version_id', sa.Integer(), nullable=True),
        sa.Column('bot_label', sa.String(length=255), nullable=False),
        sa.Column('placement', sa.Integer(), nullable=False),
        sa.Column('is_winner', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['bot_version_id'], ['bot_versions.id'], ondelete='SET NULL', use_alter=True),
        sa.ForeignKeyConstraint(['replay_id'], ['replays.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'bot_versions' not in existing_tables:
        op.create_table('bot_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bot_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('archived', sa.Boolean(), nullable=False),
        sa.Column('file_hash', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bot_id', 'version_number', name='uq_bot_version_number')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_versions')
    op.drop_table('replay_participants')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('replays')
    # ### end Alembic commands ###
